//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVMVC.Web.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int ID { get; set; }
        public string smname { get; set; }
        public string link { get; set; }
        public string icon { get; set; }
        public Nullable<bool> state { get; set; }
    }
}
